In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv(r"C:\Users\Palak\Downloads\data_cleaned.csv")
data.head(2)

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  

[2 rows x 25 columns]

In [4]:
data.isnull().sum()

Survived      0
Age           0
Fare          0
Pclass_1      0
Pclass_2      0
Pclass_3      0
Sex_female    0
Sex_male      0
SibSp_0       0
SibSp_1       0
SibSp_2       0
SibSp_3       0
SibSp_4       0
SibSp_5       0
SibSp_8       0
Parch_0       0
Parch_1       0
Parch_2       0
Parch_3       0
Parch_4       0
Parch_5       0
Parch_6       0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [5]:
data.describe()

Survived         Age        Fare    Pclass_1    Pclass_2    Pclass_3  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.383838   29.699118   32.204208    0.242424    0.206510    0.551066   
std      0.486592   13.002015   49.693429    0.428790    0.405028    0.497665   
min      0.000000    0.420000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000   22.000000    7.910400    0.000000    0.000000    0.000000   
50%      0.000000   29.699118   14.454200    0.000000    0.000000    1.000000   
75%      1.000000   35.000000   31.000000    0.000000    0.000000    1.000000   
max      1.000000   80.000000  512.329200    1.000000    1.000000    1.000000   

       Sex_female    Sex_male     SibSp_0     SibSp_1  ...     Parch_0  \
count  891.000000  891.000000  891.000000  891.000000  ...  891.000000   
mean     0.352413    0.647587    0.682379    0.234568  ...    0.760943   
std      0.477990    0.477990    0.465813    0.423966  ...    0.426747   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    1.000000   
50%      0.000000    1.000000    1.000000    0.000000  ...    1.000000   
75%      1.000000    1.000000    1.000000    0.000000  ...    1.000000   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

          Parch_1     Parch_2     Parch_3     Parch_4     Parch_5     Parch_6  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.132435    0.089787    0.005612    0.004489    0.005612    0.001122   
std      0.339154    0.286037    0.074743    0.066890    0.074743    0.033501   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

       Embarked_C  Embarked_Q  Embarked_S  
count  891.000000  891.000000  891.000000  
mean     0.188552    0.086420    0.725028  
std      0.391372    0.281141    0.446751  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    1.000000  
75%      0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 25 columns]

In [10]:
data.describe(percentiles=[0.01,0.35,0.75,0.99])

Survived         Age        Fare    Pclass_1    Pclass_2    Pclass_3  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.383838   29.699118   32.204208    0.242424    0.206510    0.551066   
std      0.486592   13.002015   49.693429    0.428790    0.405028    0.497665   
min      0.000000    0.420000    0.000000    0.000000    0.000000    0.000000   
1%       0.000000    1.000000    0.000000    0.000000    0.000000    0.000000   
35%      0.000000   26.000000    9.000000    0.000000    0.000000    0.000000   
50%      0.000000   29.699118   14.454200    0.000000    0.000000    1.000000   
75%      1.000000   35.000000   31.000000    0.000000    0.000000    1.000000   
99%      1.000000   65.000000  249.006220    1.000000    1.000000    1.000000   
max      1.000000   80.000000  512.329200    1.000000    1.000000    1.000000   

       Sex_female    Sex_male     SibSp_0     SibSp_1  ...     Parch_0  \
count  891.000000  891.000000  891.000000  891.000000  ...  891.000000   
mean     0.352413    0.647587    0.682379    0.234568  ...    0.760943   
std      0.477990    0.477990    0.465813    0.423966  ...    0.426747   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
1%       0.000000    0.000000    0.000000    0.000000  ...    0.000000   
35%      0.000000    0.000000    1.000000    0.000000  ...    1.000000   
50%      0.000000    1.000000    1.000000    0.000000  ...    1.000000   
75%      1.000000    1.000000    1.000000    0.000000  ...    1.000000   
99%      1.000000    1.000000    1.000000    1.000000  ...    1.000000   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

          Parch_1     Parch_2     Parch_3     Parch_4     Parch_5     Parch_6  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.132435    0.089787    0.005612    0.004489    0.005612    0.001122   
std      0.339154    0.286037    0.074743    0.066890    0.074743    0.033501   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
1%       0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
35%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
99%      1.000000    1.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

       Embarked_C  Embarked_Q  Embarked_S  
count  891.000000  891.000000  891.000000  
mean     0.188552    0.086420    0.725028  
std      0.391372    0.281141    0.446751  
min      0.000000    0.000000    0.000000  
1%       0.000000    0.000000    0.000000  
35%      0.000000    0.000000    1.000000  
50%      0.000000    0.000000    1.000000  
75%      0.000000    0.000000    1.000000  
99%      1.000000    1.000000    1.000000  
max      1.000000    1.000000    1.000000  

[10 rows x 25 columns]

In [16]:
data["Survived"].value_counts(normalize=True)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [17]:
x=data.iloc[:,1:]

In [19]:
y=data[["Survived"]]


In [23]:
from sklearn.preprocessing import StandardScaler
a=StandardScaler()
x_scaler=a.fit_transform(x)

In [24]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x_scaler,y,test_size=0.30,random_state=22,stratify=y)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
Log_reg=LogisticRegression()

In [28]:
Log_reg.fit(x_train,y_train)

C:\Users\Palak\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [29]:
y_test_predict=Log_reg.predict(x_test)

In [30]:
y_train_predict=Log_reg.predict(x_train)

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,roc_curve,roc_auc_score

In [40]:
accuracy=accuracy_score(y_test,y_test_predict)
accuracy

0.8134328358208955

In [41]:
con_matr=confusion_matrix(y_test,y_test_predict)
con_matr

array([[140,  25],
       [ 25,  78]], dtype=int64)

In [45]:
class_report=classification_report(y_test,y_test_predict)
print(class_report)

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       165
           1       0.76      0.76      0.76       103

    accuracy                           0.81       268
   macro avg       0.80      0.80      0.80       268
weighted avg       0.81      0.81      0.81       268



In [49]:
fpr, tpr, thresholds = roc_curve(y_test, y_test_predict)

In [50]:
fpr

array([0.        , 0.15151515, 1.        ])

In [51]:
tpr

array([0.        , 0.75728155, 1.        ])

In [52]:
thresholds

array([2, 1, 0], dtype=int64)

In [56]:
auc = roc_auc_score(y_test, y_test_predict)
auc

0.8028832009414534